GET https://afternoon-mesa-16188.herokuapp.com/api/persons/3

###
GET http://localhost:3001/api/persons/

###
GET https://afternoon-mesa-16188.herokuapp.com/api/persons
###
DELETE https://afternoon-mesa-16188.herokuapp.com/api/persons/44140

###
POST https://afternoon-mesa-16188.herokuapp.com/api/persons
Content-Type: application/json

{
    "name" : "Sara",
    "number" : "13131"
}

###
POST https://afternoon-mesa-16188.herokuapp.com/api/persons
Content-Type: application/json

{
    "name" : "Sami",
    "number" : "9911"
}

###
GET http://localhost:3001/info
###
GET http://localhost:3001/13123