#### Localhost
GET http://localhost:3001/api/persons/
###
GET http://localhost:3001/api/persons/607fe8a912ca370680ea64b3
###
DELETE  http://localhost:3001/api/persons/608005646221b90a8d856f3d
###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name" : "Sa",
    "number" : "131319991"
}
###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name" : "Sami",
    "number" : "9911"
}
###
GET http://localhost:3001/info


#### Heroku
###
GET https://afternoon-mesa-16188.herokuapp.com/api/persons/44140
###
DELETE https://afternoon-mesa-16188.herokuapp.com/api/persons/44140
###
POST https://afternoon-mesa-16188.herokuapp.com/api/persons
Content-Type: application/json

{
    "name" : "Sara",
    "number" : "13131"
}
###
POST https://afternoon-mesa-16188.herokuapp.com/api/persons
Content-Type: application/json

{
    "name" : "Sami",
    "number" : "9911"
}
